import type { Metadata } from 'next';
import './styles/index.css';
import AppGuard from './config/provider/AppProvider';
import { Suspense } from 'react';
import Loading from './components/loading/loading';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="w-full flex flex-col">
          <Suspense fallback={<Loading />}>
            <AppGuard isLoading={<Loading /> ? true : false}>
              {children}
            </AppGuard>
          </Suspense>
        </main>
      </body>
    </html>
  );
}
